services:
  - type: web
    name: chatterfrontend
    env: static
    buildCommand: npm ci && npm run build && echo "Build completed, checking _redirects..." && ls -la dist/ && cat dist/_redirects
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - key: Cache-Control
        value: no-cache
    pullRequestPreviewsEnabled: false
